# Generated by Django 3.1.5 on 2021-01-20 19:25

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='film_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='film',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 20, 19, 25, 25, 603316, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='film',
            name='views_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
