# Generated by Django 3.1.5 on 2021-01-20 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20210120_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
