# Generated by Django 3.1.5 on 2021-01-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0003_auto_20210120_1926"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="rating",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
    ]
