# Generated by Django 3.1.5 on 2021-01-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0005_auto_20210121_2000"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="video",
            field=models.FileField(blank=True, upload_to="videos"),
        ),
    ]
