# Generated by Django 3.1.5 on 2021-01-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_auto_20210124_2002'),
        ('films', '0008_auto_20210124_1249'),
    ]

    operations = [
    ]
