# Generated by Django 3.1.5 on 2021-01-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_film_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='gif',
            field=models.ImageField(blank=True, upload_to='gifs'),
        ),
    ]
