# Generated by Django 3.1.5 on 2021-01-30 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0009_auto_20210128_2244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="publication_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
