# Generated by Django 3.1.5 on 2021-01-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
