# Generated by Django 3.1.5 on 2021-01-31 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0010_auto_20210130_2019"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
