# Generated by Django 3.1.5 on 2021-01-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_auto_20210128_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
