# Generated by Django 3.1.5 on 2021-01-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='gif',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
