# Generated by Django 3.1.5 on 2021-01-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_auto_20210128_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='gif',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
