# Generated by Django 3.1.5 on 2021-01-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_auto_20210128_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='gif',
            field=models.FileField(blank=True, upload_to='gifs'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters'),
        ),
    ]
