version: "3.0"

services:
  db:
    image: postgres
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/filmbook
    ports:
      - "8000:8000"
    depends_on:
      - migrations
      - db
  migrations:
      build:
        context: .
      command: python manage.py migrate --noinput
      volumes:
        - .:/filmbook
      depends_on:
        - db