version: "3.0"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/filmbook
    ports:
      - "8000:8000"

  migration:
    image: filmbook_webapp:latest
    command: python manage.py migrate --noinput
